# Generated by cask-dotfile-generator
# Created by: @seethroughtrees
# https://github.com/seethroughtrees/brew-cask-dotfile-generator


install atlassian-plugin-sdk
install autoconf
install automake
install brew-cask
install cmake
install cscope
install flow
install freetype
install fzf
install gdbm
install gettext
install go
install hub
install icu4c
install jpeg
install libevent
install libpng
install libtool
install macvim
install mozilla-addon-sdk
install msgpack
install neovim
install node
install openssl
install pcre
install php56
install php56-xdebug
install pkg-config
install scons
install terminal-notifier
install the-silver-searcher
install tmux
install tree
install unixodbc
install watch
install xz
install zlib
install zsh
