# Generated by cask-dotfile-generator
# Created by: @seethroughtrees
# https://github.com/seethroughtrees/brew-cask-dotfile-generator


install brew-cask
install cscope
install fzf
install gdbm
install macvim
install node
install pcre
install terminal-notifier
install the-silver-searcher
install xz
install zsh
